# Generated by Django 3.1.6 on 2021-02-17 15:09

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to=movies.models.Actor.file_rename, verbose_name='Изображение'),
        ),
    ]
