# Generated by Django 3.1.6 on 2021-02-22 14:28

import datetime
from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210217_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=movies.models.Movie.file_rename, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Премьера в мире'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='image',
            field=models.ImageField(upload_to='movie_shots/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
