# Generated by Django 3.1.6 on 2021-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210222_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshots',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
